version: '3.4'

x-system-addr-env: &system-addr-env
  # private key: a6aecc98b63bafb0de3b29ae9964b14acb4086057808be29f90150214ebd4a0f
  # OK to publish this since it will only ever be used in itests
  SYSTEM_ADDRESS_0_DEPLOYER: '0xa961b0d6dce82db098cf70a42a14add3ee3db2d5'

  # private key: 3b8d2345102cce2443acb240db6e87c8edd4bb3f821b17fab8ea2c9da08ea132
  # OK to publish this since it will only ever be used in itests
  SYSTEM_ADDRESS_1_DEPLOYER: '0xdfc82d475833a50de90c642770f34a9db7deb725'

services:
  # this is a helper service used because there's no official hardhat image
  # l1_chain:
  #   image: onthertech/optimism.hardhat:${DOCKER_TAG_HARDHAT:-latest}
  #   build:
  #     context: ./docker/hardhat
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./envs/l1_chain.env
  #   ports:
  #     # expose the service to the host for integration testing
  #     - ${L1CHAIN_HTTP_PORT:-9545}:8545

  deployer:
    build:
        context: ..
        dockerfile: ./ops/docker/Dockerfile.packages
        target: deployer-hardhat-remote
    image: onthertech/optimism.deployer:${DOCKER_TAG_DEPLOYER:-latest}
    entrypoint: ./deployer-hardhat-remote.sh
    environment:
      # Env vars for the deployment script.
      CONTRACTS_RPC_URL: ${L1_NODE_WEB3_URL}
      CONTRACTS_DEPLOYER_KEY: ${CONTRACTS_DEPLOYER_KEY}
      CONTRACTS_TARGET_NETWORK: ${CONTRACTS_TARGET_NETWORK}
    ports:
      # expose the service to the host for getting the contract addrs
      - ${DEPLOYER_PORT:-8080}:8081
    networks:
      - optimism


  dtl:
    depends_on:
      - l2geth
    image: onthertech/optimism.data-transport-layer:${TAG:-latest}
    entrypoint: ./dtl.sh
    env_file:
      -  ./envs/dtl.env
    environment:
      URL: ${DEPLOYER_ADDRESS_URL}
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: ${L1_NODE_WEB3_URL}
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: ${L2_NODE_WEB3_URL}
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: ${SYNC_FROM_L1:-true}
      DATA_TRANSPORT_LAYER__L1_START_HEIGHT: ${L1_START_HEIGHT:-1}
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: ${L2_CHAIN_ID}
      RETRIES: 120
    ports:
      - ${DTL_PORT:-7878}:7878
    networks:
      - optimism

  l2geth:
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: onthertech/optimism.l2geth:${DOCKER_TAG_L2GETH:-latest}
    # override with the geth script and the env vars required for it
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    environment:
      <<: *system-addr-env
      ETH1_HTTP: ${L1_NODE_WEB3_URL}
      CHAIN_ID: ${L2_CHAIN_ID}
      NETWORK_ID: ${L2_CHAIN_ID}
      ROLLUP_TIMESTAMP_REFRESH: ${ROLLUP_TIMESTAMP_REFRESH}
      ROLLUP_STATE_DUMP_PATH: ${ROLLUP_STATE_DUMP_PATH}
      ROLLUP_CLIENT_HTTP: ${ROLLUP_CLIENT_HTTP}
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 120
      # no need to keep this secret, only used internally to sign blocks
      L2_TOKAMAK_TOKEN_ADDRESS: "0x4200000000000000000000000000000000000023"
      TOKAMAK_GAS_PRICE_ORACLE_ADDRESS: "0x4200000000000000000000000000000000000024"
      ROLLUP_ENFORCE_FEES: ${ROLLUP_ENFORCE_FEES:-false}
      ROLLUP_FEE_THRESHOLD_DOWN: 0.9
      ROLLUP_FEE_THRESHOLD_UP: 1.1
    ports:
      - ${L2GETH_HTTP_PORT:-8545}:8545
      - ${L2GETH_WS_PORT:-8546}:8546
    networks:
      - optimism

  relayer:
    depends_on:
      - l2geth
    deploy:
      replicas: 1
    image: onthertech/optimism.message-relayer:${DOCKER_TAG_MESSAGE_RELAYER:-latest}
    entrypoint: ./relayer.sh
    environment:
      URL: ${DEPLOYER_ADDRESS_URL}
      MESSAGE_RELAYER__L1_RPC_PROVIDER: ${L1_NODE_WEB3_URL_FOR_RELAYER}
      MESSAGE_RELAYER__L2_RPC_PROVIDER: ${L2_NODE_WEB3_URL}
      MESSAGE_RELAYER__L1_WALLET: ${L1_WALLET_KEY}
      RETRIES: 120
    networks:
      - optimism

  batch_submitter:
    depends_on:
      - l2geth
    image: onthertech/optimism.batch-submitter-service:${DOCKER_TAG_BATCH_SUBMITTER_SERVICE:-latest}
    entrypoint: ./batch-submitter.sh
    env_file:
      - ./envs/batch-submitter.env
    environment:
      L1_ETH_RPC: ${L1_NODE_WEB3_URL}
      L2_ETH_RPC: ${L2_NODE_WEB3_URL}
      URL: ${DEPLOYER_ADDRESS_URL}
      BATCH_SUBMITTER_SEQUENCER_PRIVATE_KEY: ${SEQUENCER_PRIVATE_KEY}
      BATCH_SUBMITTER_PROPOSER_PRIVATE_KEY: ${PROPOSER_PRIVATE_KEY}
      BATCH_SUBMITTER_SEQUENCER_BATCH_TYPE: ${BATCH_SUBMITTER_SEQUENCER_BATCH_TYPE:-zlib}
      RETRIES: 120
    networks:
      - optimism

networks:
  optimism:
    driver: bridge
