name: bss-core tests

on:
  push:
    paths:
      - 'bss-core/**'
  pull_request:
    paths:
      - 'bss-core/**'
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: './bss-core'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: bss-core

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unit Test
        run: go test -v ./...
