name: l2geth tests

on:
  push:
    paths:
      - 'l2geth/**'
  pull_request:
    paths:
      - 'l2geth/**'
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: './l2geth'

jobs:
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.18

  #     - uses: actions/checkout@v3

  #     - name: Lint
  #       run: make lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: make

      - name: Unit Test
        run: make test
